# Generated by Django 5.2.8 on 2026-01-01 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=300)),
                ('telephone', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siret', models.CharField(max_length=14, unique=True)),
                ('date_creation', models.DateField(blank=True, null=True)),
                ('statut_admin', models.CharField(blank=True, max_length=250, null=True)),
                ('nom_officiel', models.CharField(blank=True, max_length=90, null=True)),
                ('autres_noms', models.TextField(blank=True, max_length=250, null=True)),
                ('prenom_dirigeant', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prediagnostique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.TextField()),
                ('sous_traitee', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('texte_question', models.TextField()),
                ('type', models.CharField(choices=[('single', 'Choix unique'), ('multiple', 'Choix multiple')], max_length=10)),
                ('choices', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Dossiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_dossier', models.CharField(choices=[('QUALIBAT', 'QUALIBAT'), ('QUALIT_ENR', 'QUALIT’ENR'), ('AEAO', 'AUDIT ENERGETIQUE AFNOR & OPQIBI'), ('CERTIBAT', 'CERTIBAT'), ('QUALIF_ELEC', 'QUALIF’ELEC'), ('AMO', 'Accompagnateur Rénov')], max_length=50)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('Incomplet', 'Incomplet'), ('validé', 'Validé')], default='en_attente', max_length=30)),
                ('eligibilite_estimee', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.contact')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='clients.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_user', models.JSONField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='clients.contact')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='clients.dossiers')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='clients.question')),
            ],
        ),
    ]
