# Generated by Django 5.2.8 on 2025-12-09 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=300)),
                ('telephone', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=5)),
                ('siret', models.CharField(max_length=14, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('statut_admin', models.CharField(blank=True, max_length=250, null=True)),
                ('nom_officiel', models.CharField(blank=True, max_length=90, null=True)),
                ('autres_noms', models.TextField(blank=True, max_length=250, null=True)),
                ('prenom_dirigeant', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Prediagnostique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('reponse', models.TextField()),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dossiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_dossier', models.CharField(choices=[('QUALIBAT', 'QUALIBAT'), ('QUALIT_ENR', 'QUALIT’ENR'), ('AEAO', 'AUDIT ENERGETIQUE AFNOR & OPQIBI'), ('CERTIBAT', 'CERTIBAT'), ('QUALIF_ELEC', 'QUALIF’ELEC'), ('AMO', 'Accompagnateur Rénov')], max_length=50)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('Incomplet', 'Incomplet'), ('validé', 'Validé')], default='en_attente', max_length=30)),
                ('eligibilite_estimee', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='clients.client')),
            ],
        ),
    ]
