# Generated by Django 5.2.8 on 2025-12-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_creation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
