# Generated by Django 5.2.8 on 2025-12-24 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('texte_question', models.TextField()),
                ('type', models.CharField(choices=[('single', 'Choix unique'), ('multiple', 'Choix multiple')], max_length=10)),
                ('choices', models.JSONField(default=list)),
            ],
        ),
        migrations.RemoveField(
            model_name='prediagnostique',
            name='question',
        ),
        migrations.AddField(
            model_name='prediagnostique',
            name='sous_traitee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_creation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_user', models.JSONField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='clients.client')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='clients.question')),
            ],
        ),
    ]
