# Generated by Django 5.2.8 on 2025-12-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediagnostique',
            name='sous_traitance',
            field=models.BooleanField(default=False),
        ),
    ]
