# Generated by Django 5.2.8 on 2026-01-16 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rendezvous'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilite_rdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_time', models.DateTimeField()),
                ('proposed_day', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.contact')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_requests', to='clients.dossiers')),
            ],
        ),
    ]
