# Generated by Django 5.2.8 on 2025-12-16 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_prediagnostique_sous_traitance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prediagnostique',
            old_name='sous_traitance',
            new_name='sous_traitee',
        ),
    ]
