# Generated by Django 5.2.8 on 2025-12-18 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_rename_sous_traitance_prediagnostique_sous_traitee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prediagnostique',
            name='question',
        ),
    ]
